version: 2

updates:
  - package-ecosystem: "npm"
    directory: "site/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "site_guides/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
